


# foxglove
foxglove_ws_uri: ws://localhost:8765
foxglove_ws_subprotocol: foxglove.websocket.v1

# bing api key
bing_api_key: "AkCDUXwYzM3w36XYcNeT0kNOFhpTiQuwluXkQlFBs1WhFbknP2_2iDBXeL_WzXCc"

# container
container_image: "ghcr.io/serene4mr/mowbot_legacy:latest"
container_stop_timeout: 1


# others
mowbot_legacy_data_path: "/mowbot_legacy_data"
waypoints_file: "__waypoints__.yaml"
nav_params_file: "__nav_params__.yaml"
ntrip_params_file: "__ntrip_params__.yaml"